name: Pipeline DockerHub Dev

on:
  release:
    types:
      - "published"

env:
  REPO_NAME: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Configurar variable de entorno con el nombre del repositorio
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Extract tag name
        id: tag_name
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}

      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dev-${{ env.REPO_NAME }}:latest
